name: Search for Resumes

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  search-resumes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure the correct version

      - name: Debug - Check GitHub Token
        run: |
          echo "GitHub Token: ${{ secrets.GITHUB_TOKEN }}"
          echo "Starting resume search..."
      
      - name: Search for Resumes
        run: |
          # Define your search term and file type
          SEARCH_TERM="resume"
          FILE_TYPE="pdf"

          # Use the GitHub API to search for files
          curl -s "https://api.github.com/search/code?q=$SEARCH_TERM+in:file+extension:$FILE_TYPE" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" > results.json
          
          echo "Results saved to results.json"
          cat results.json  # Output the results for debugging
      
      - name: Commit Results
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add results.json
          git commit -m "Add resume search results"
          git push origin main
